name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'How beautiful to be here with me珞'' first issue'
        pr-message: 'Gantaashana Waan Qabaa Martina Guulaan u Ahay'' first pr'
